# app/utils/builder.py
class DailyDigestBuilder:
    def __init__(self):
        self.digest_text = ""

    def add_header(self, date_str: str):
        self.digest_text += f"=========================================\n"
        self.digest_text += f"   YOUR DAILY AI DIGEST - {date_str}   \n"
        self.digest_text += f"=========================================\n\n"
        return self # Returning self allows method chaining

    def add_section(self, category: str, articles: list):
        self.digest_text += f"--- {category.upper()} ---\n"
        for art in articles:
            self.digest_text += f"📌 {art.title}\n"
            self.digest_text += f"Summary: {art.summary}\n"
            self.digest_text += f"Read more: {art.url}\n\n"
        return self

    def add_footer(self):
        self.digest_text += f"=========================================\n"
        self.digest_text += f"Generated by Llama 3 on Groq. Have a great day!\n"
        return self

    def build(self) -> str:
        return self.digest_text